name: k6 test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'K6 Load Test'  

jobs:
  k6_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: longwuyuan/ingress-nginx
          ref: k6

      - name: Create cluster
        working-directory: /home/runner/work/k6-loadtest-example
        continue-on-error: true
        run: |
          mkdir $HOME/.kube
          which kubectl
          which kind
          cd ingress-nginx
          make dev-env
          sleep 30
          kubectl get po -A
          kubectl create deploy k6 --image nginx:alpine --port 80 && kubectl expose deploy k6 --port 80 && kubectl create ing k6 --class nginx --rule localhost/=k6:80
          sleep 30
          kubectl get all,ing
          curl localhost
 
      - name: Run k6 test
        run: |
          cd test/k6
          ./k6 run ./k6.test.js
