name: k6 test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'K6 Load Test'  

jobs:
  k6_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: longwuyuan/ingress-nginx
          ref: k6

      - name: Create cluster
        working-directory: /home/runner/work/k6-loadtest-example
        continue-on-error: true
        run: |
          id
          mkdir $HOME/bin
          mkdir $HOME/.kube
          export PATH=$PATH:$HOME/bin
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.13.0/kind-linux-amd64
          chmod +x ./kind
          mv kind $HOME/bin/kind
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl $HOME/bin
          which kubectl
          which kind
          ls -lath $HOME/bin
          pwd
          ls -la
          cd ingress-nginx
          ls -la
          make dev-env
          sleep 100
          kubectl get po -A
          kubectl create deploy k6 --image nginx:alpine --port 80 && kubectl expose deploy k6 --port 80 && kubectl create ing k6 --class nginx --rule k6-test.ingress-nginx.local/=k6:80
          sleep 30
          kubectl get all,ing
          curl -H "Host:k6-test.ingress-nginx.local" localhost
          
      - name: Run k6 test
        uses: k6io/action@v0.1
        with:
          filename: /home/runner/work/k6-loadtest-example/k6-loadtest-example/test.js
