name: k6 cloud test
on: 
  push:
    branches: "*"

jobs:
  k6_cloud_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: longwuyuan/ingress-nginx
          ref: k6

      - name: Create cluster
        working-directory: /home/runner/work/k6-loadtest-example
        continue-on-error: true
        run: |
          id
          mkdir $HOME/bin
          mkdir $HOME/.kube
          export PATH=$PATH:$HOME/bin
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.13.0/kind-linux-amd64
          chmod +x ./kind
          mv kind $HOME/bin/kind
          which kind
          kind get clusters
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl $HOME/bin
          which kubectl
          ls -lath $HOME/bin
          pwd
          ls -la
          cd ingress-nginx
          ls -la
          make dev-env
          kind get clusters
          kubectl config get-contexts
          sleep 10
          kubectl get all,nodes -o wide
          kubectl create deploy k6 --image nginx:alpine --port 80 && kubectl expose deploy k6 --port 80 && kubectl create ing k6 ---class nginx --rule k6-test.ingress-nginx.local/=k6:80k6-test.ingress-nginx.local/=k6:80
          sleep 10
          kubectl get all,ing
          
      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: /home/runner/work/k6-loadtest-example/k6-loadtest-example/test.js
