name: k6 cloud test
on: 
  push:

jobs:
  k6_cloud_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Checkout ingress-nginx
        shell: apt-get install git -y

      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: test.js
