name: Performance Test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Load Test with K6'  

jobs:
  performance_test_with_k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: longwuyuan/ingress-nginx
          ref: k6

      - name: Create cluster
        working-directory: /home/runner/work/k6-loadtest-example/ingress-nginx
        run: |
          mkdir $HOME/.kube
          make dev-env
          sleep 60
          kubectl get all -A

      - name: Create Workload
        working-directory: /home/runner/work/k6-loadtest-example/ingress-nginx
        run: |
          kubectl create deploy k6 --image nginx:alpine --port 80 && kubectl expose deploy k6 --port 80 && kubectl create ing k6 --class nginx --rule localhost/=k6:80
          sleep 15
          kubectl get all,ing
          curl localhost
 
      - name: Downlaod k6 executable
        working-directory: /home/runner/work/k6-loadtest-example/ingress-nginx
        run: |
          pwd
          cd test/k6
          ls -l 
          wget https://github.com/grafana/k6/releases/download/v0.38.2/k6-v0.38.2-linux-amd64.tar.gz
          tar xvf k6-v0.38.2-linux-amd64.tar.gz k6-v0.38.2-linux-amd64/k6
          mv k6-v0.38.2-linux-amd64/k6 .

      - name: Run LoadTest with K6
        working-directory: /home/runner/work/k6-loadtest-example/ingress-nginx
        run: ./k6 run ./k6.test.js
