name: Smoke Test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Load Test with K6'  

jobs:
  Smoke_Test_using_k6:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: longwuyuan/ingress-nginx
          ref: k6

      - name: Downlaod k6 executable
        working-directory: /home/runner/work/k6-loadtest-example/k6-loadtest-example
        run: |
          wget https://github.com/grafana/k6/releases/download/v0.38.2/k6-v0.38.2-linux-amd64.tar.gz
          tar xvf k6-v0.38.2-linux-amd64.tar.gz k6-v0.38.2-linux-amd64/k6
          mv k6-v0.38.2-linux-amd64/k6 .
          ./k6
          
      - name: Create cluster
        working-directory: /home/runner/work/k6-loadtest-example/ingress-nginx
        run: |
          mkdir $HOME/.kube
          make dev-env
          echo "..sleeping 5secs to get controller podname"
          sleep 5
          echo "..waiting for controller pod to be Running"
          kubectl wait pod -n ingress-nginx --for condition=Ready \
            `kubectl get po -n ingress-nginx | grep controller | awk '{print $1}'` --timeout=75s
          echo "..listing cluster resources"
          kubectl get all -A

      - name: Create Workload
        working-directory: /home/runner/work/k6-loadtest-example/ingress-nginx
        env:
          CERT: ${{ secrets.CERT_INGRESSNGINXCONTROLLER }}
          PRIVKEY: ${{ secrets.PRIVKEY_INGRESSNGINXCONTROLLER }}
        run: |
          echo $CERT | base64 --decode > certificate.crt
          echo $PRIVKEY | base64 --decode > private.key
          echo "..creating the tls secret"
          kubectl create secret tls certificate.test.ingress-nginx-controller.ga \
            --cert certificate.crt \
            --key private.key
          echo "..creating deployment, service & ingress to test"
          kubectl create deploy k6 --image kennethreitz/httpbin --port 80 && \
            kubectl expose deploy k6 --port 80 && \
            kubectl create ing k6 --class nginx \
            --rule "test.ingress-nginx-controller.ga/*=k6:80,tls=certificate.test.ingress-nginx-controller.ga"
          echo "..sleeping 5secs to get podname"
          sleep 5
          echo "..waiting for pod to be Running"
          kubectl wait pod --for condition=Ready `kubectl get po | grep k6 | awk '{print $1}'`
          kubectl get all,secrets,ing 

      - name: Run k6 LoadTest
        working-directory: /home/runner/work/k6-loadtest-example/k6-loadtest-example
        run: |
          vmstat -at 5 | tee vmstat_report &
          ./k6 run ./smoketest.js
          pkill vmstat
          cat vmstat_report
